name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get update
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/gemini-flask-app .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/gemini-flask-app

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials producer-cluster --zone us-west1-a --project ${{ secrets.GCP_PROJECT }}

    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic gemini-api-key --from-literal=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to GKE
      run: |
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml
